### ISSUE TITLE
network interface type detection under Linux is unreliable

### ISSUE THREAD

**Issue by terceiro** [threez/ruby-vmstat#22]
Hi, assuming the interface type from their name is misleading, since interfaces can have arbitrary names.

```ruby
type = case columns[0]
  when /^eth/ then NetworkInterface::ETHERNET_TYPE
  when /^lo/  then NetworkInterface::LOOPBACK_TYPE
end
```
also, the test for the  the loopback filtering assumes there is always a single loopback interface. For example, when vmstat was being [built for the Debian mips architecture](https://buildd.debian.org/status/fetch.php?pkg=ruby-vmstat&arch=mips&ver=2.3.0-1&stamp=1518644579&raw=0), the machine running the build had 5 loopback interfaces (for reasons that are not relevant here), and that made the tests fail:

```
Failures:

  1) Vmstat Vmstat#filter_devices should filter loopback devices
     Failure/Error: Vmstat.loopback_devices.size.should == 1

       expected: 1
            got: 5 (using ==)
     # ./spec/vmstat_spec.rb:25:in `block (3 levels) in <top (required)>'
```

maybe that test should look for at least, but not exactly, one loopback. or perhaps actually testing the type of the returned interfaces, instead of how many of them are returned.
